"""Module reset catalog — metadata for Super Admin UI."""

from __future__ import annotations

MODULE_KEYS = (
    "sales",
    "purchases",
    "payments",
    "expenses",
    "quotations",
    "inventory",
    "customers",
    "suppliers",
    "products",
    "tax",
    "reports",
    "treasury",
)

MODULE_CATALOG = [
    {
        "key": "sales",
        "label_ar": "المبيعات",
        "label_en": "Sales",
        "danger_level": "high",
        "description_ar": "حذف فواتير البيع وتأثيراتها على العملاء والمخزون",
        "description_en": "Delete sales invoices and related customer/inventory effects",
        "requires_confirmation": True,
    },
    {
        "key": "purchases",
        "label_ar": "المشتريات",
        "label_en": "Purchases",
        "danger_level": "high",
        "description_ar": "حذف فواتير الشراء وتأثيراتها على الموردين والمخزون",
        "description_en": "Delete purchase invoices and related supplier/inventory effects",
        "requires_confirmation": True,
    },
    {
        "key": "payments",
        "label_ar": "المدفوعات",
        "label_en": "Payments",
        "danger_level": "high",
        "description_ar": "حذف التحصيلات والمدفوعات والتخصيصات",
        "description_en": "Delete collections, payments, refunds, and allocations",
        "requires_confirmation": True,
    },
    {
        "key": "expenses",
        "label_ar": "المصروفات",
        "label_en": "Expenses",
        "danger_level": "medium",
        "description_ar": "حذف المصروفات وحركات الخزينة المرتبطة",
        "description_en": "Delete expenses and related treasury movements",
        "requires_confirmation": True,
    },
    {
        "key": "quotations",
        "label_ar": "عروض الأسعار",
        "label_en": "Quotations",
        "danger_level": "medium",
        "description_ar": "حذف عروض الأسعار فقط",
        "description_en": "Delete quotation documents only",
        "requires_confirmation": True,
    },
    {
        "key": "inventory",
        "label_ar": "المخزون",
        "label_en": "Inventory",
        "danger_level": "critical",
        "description_ar": "حذف أرصدة المخزون وطبقات FIFO وحركات المخزون",
        "description_en": "Delete stock balances, FIFO layers, and movements",
        "requires_confirmation": True,
    },
    {
        "key": "customers",
        "label_ar": "العملاء",
        "label_en": "Customers",
        "danger_level": "high",
        "description_ar": "حذف سجلات العملاء والأسعار الخاصة",
        "description_en": "Delete customer master data and special prices",
        "requires_confirmation": True,
    },
    {
        "key": "suppliers",
        "label_ar": "الموردين",
        "label_en": "Suppliers",
        "danger_level": "high",
        "description_ar": "حذف سجلات الموردين والأسعار الخاصة",
        "description_en": "Delete supplier master data and special prices",
        "requires_confirmation": True,
    },
    {
        "key": "products",
        "label_ar": "المنتجات",
        "label_en": "Products",
        "danger_level": "high",
        "description_ar": "حذف المنتجات والفئات",
        "description_en": "Delete products and categories",
        "requires_confirmation": True,
    },
    {
        "key": "tax",
        "label_ar": "الضريبة",
        "label_en": "Tax",
        "danger_level": "medium",
        "description_ar": "حذف تحذيرات الضريبة والتعديلات والفترات غير المقفلة",
        "description_en": "Delete tax warnings, adjustments, and open periods",
        "requires_confirmation": True,
    },
    {
        "key": "reports",
        "label_ar": "التقارير",
        "label_en": "Reports",
        "danger_level": "low",
        "description_ar": "حذف لقطات التقارير المخزنة فقط (إن وجدت)",
        "description_en": "Delete stored report snapshots/cache only",
        "requires_confirmation": True,
    },
    {
        "key": "treasury",
        "label_ar": "الخزينة",
        "label_en": "Treasury",
        "danger_level": "high",
        "description_ar": "حذف حسابات النقد والبنك وحركاتها",
        "description_en": "Delete cashbox/bank accounts and movements",
        "requires_confirmation": True,
    },
]
