# Generated by Django 5.1.4 on 2026-06-30 12:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_approved', 'Purchase Approved'), ('sales_approved', 'Sales Approved'), ('sales_cancelled', 'Sales Cancelled'), ('purchase_cancelled', 'Purchase Cancelled'), ('manual_increase', 'Manual Increase'), ('manual_decrease', 'Manual Decrease'), ('correction', 'Correction'), ('stocktaking_increase', 'Stocktaking Increase'), ('stocktaking_decrease', 'Stocktaking Decrease'), ('opening_inventory', 'Opening Inventory'), ('reversal', 'Reversal')], max_length=24)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('neutral', 'Neutral')], max_length=8)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('cartons_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('pieces_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('kg_delta', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('balance_cartons_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance_pieces_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance_kg_after', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fifo_cost_consumed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('correction', 'Correction')], max_length=12)),
                ('current_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('adjustment_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('adjustment_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('adjustment_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('new_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('new_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('new_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='stock_adjustments/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reversed', 'Reversed')], default='applied', max_length=12)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_applied', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
                ('related_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('count_date', models.DateField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktaking_sessions_applied', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktaking_sessions_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('system_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('system_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('actual_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('difference_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('difference_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('difference_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('increase', 'Increase'), ('decrease', 'Decrease'), ('needs_review', 'Needs Review')], default='matched', max_length=12)),
                ('unit_cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktaking_lines', to='products.product')),
                ('related_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktaking_line', to='inventory.stockmovement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktakingsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FIFOStockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('manual_increase', 'Manual Increase'), ('stocktaking_increase', 'Stocktaking Increase'), ('opening_inventory', 'Opening Inventory'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=24)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('original_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('original_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('original_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remaining_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remaining_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remaining_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost_per_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_depleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layers', to='products.product')),
            ],
            options={
                'ordering': ['received_at', 'created_at', 'id'],
                'indexes': [models.Index(fields=['company', 'product', 'is_depleted', 'received_at'], name='inventory_f_company_af1c2e_idx'), models.Index(fields=['company', 'source_type', 'source_id'], name='inventory_f_company_795e7d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('remaining_cartons__gte', 0), ('remaining_pieces__gte', 0), ('remaining_kg__gte', 0), ('unit_cost_per_kg__gte', 0), ('total_cost__gte', 0)), name='fifo_layer_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('last_stocktaking_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balance', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'product'], name='inventory_i_company_9a41bc_idx'), models.Index(fields=['company', 'available_kg'], name='inventory_i_company_a3523a_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'product'), name='uniq_company_product_balance'), models.CheckConstraint(condition=models.Q(('available_cartons__gte', 0), ('available_pieces__gte', 0), ('available_kg__gte', 0)), name='inventory_balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InventoryValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_available_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
                'indexes': [models.Index(fields=['company', 'snapshot_date'], name='inventory_i_company_8879ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'product', 'created_at'], name='inventory_s_company_0ef626_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'movement_type'], name='inventory_s_company_339f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='inventory_s_company_e7ee98_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_cartons_after__gte', 0), ('balance_pieces_after__gte', 0), ('balance_kg_after__gte', 0)), name='stock_movement_balance_after_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['company', 'product', 'applied_at'], name='inventory_s_company_6f793d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['company', 'adjustment_type'], name='inventory_s_company_783867_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakingsession',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_6b0ae2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakingsession',
            constraint=models.UniqueConstraint(fields=('company', 'session_number'), name='uniq_company_stocktaking_session_number'),
        ),
        migrations.AddIndex(
            model_name='stocktakingline',
            index=models.Index(fields=['company', 'session'], name='inventory_s_company_327933_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakingline',
            constraint=models.UniqueConstraint(fields=('session', 'product'), name='uniq_session_product_line'),
        ),
    ]
