# Generated by Django 5.1.15 on 2026-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifostocklayer',
            name='source_type',
            field=models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('sales_invoice', 'Sales Invoice'), ('manual_increase', 'Manual Increase'), ('stocktaking_increase', 'Stocktaking Increase'), ('opening_inventory', 'Opening Inventory'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=24),
        ),
    ]
