# Generated by Django 5.1.15 on 2026-07-09 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_movement_date'),
        ('products', '0001_initial'),
        ('tenants', '0003_company_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'product', 'movement_date'], name='inventory_s_company_c4a51e_idx'),
        ),
    ]
