# Generated by Django 5.1.15 on 2026-06-30 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=64)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=64)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit / On Account'), ('other', 'Other')], default='credit', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('inventory_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('supplier_trn_snapshot', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('approval_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='purchase_attachments/')),
                ('file_type', models.CharField(choices=[('supplier_invoice', 'Supplier Invoice'), ('delivery_note', 'Delivery Note'), ('receipt', 'Receipt'), ('other', 'Other')], default='supplier_invoice', max_length=16)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('supplier_deduction', 'Supplier Deduction'), ('add_to_inventory_cost', 'Add to Inventory Cost'), ('normal_expense_later', 'Normal Expense (later)'), ('commercial_discount', 'Commercial Discount'), ('transport_cost', 'Transport Cost'), ('slaughter_cost', 'Slaughter Cost'), ('loading_unloading', 'Loading / Unloading'), ('other', 'Other')], max_length=24)),
                ('effect', models.CharField(choices=[('reduce_supplier_payable', 'Reduce Supplier Payable'), ('increase_inventory_cost', 'Increase Inventory Cost'), ('expense_only_later', 'Expense Only (later)'), ('no_financial_effect', 'No Financial Effect')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('product_sku_snapshot', models.CharField(blank=True, max_length=64)),
                ('line_type', models.CharField(choices=[('product', 'Product'), ('by_product', 'By-product'), ('service', 'Service'), ('other', 'Other')], default='product', max_length=16)),
                ('quantity_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_type', models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece'), ('carton', 'Per Carton'), ('tray', 'Per Tray')], default='kg', max_length=10)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost_per_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='products.product')),
            ],
            options={
                'ordering': ['invoice', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=16)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_status_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', 'supplier'], name='purchases_p_company_b04bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_81ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', 'invoice_date'], name='purchases_p_company_2ef36c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', 'payment_status'], name='purchases_p_company_f77a38_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_company_purchase_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_invoice_number', ''), _negated=True), fields=('company', 'supplier', 'supplier_invoice_number'), name='uniq_company_supplier_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseattachment',
            index=models.Index(fields=['company', 'invoice'], name='purchases_p_company_58dac1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseadjustment',
            index=models.Index(fields=['company', 'invoice'], name='purchases_p_company_275849_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['company', 'invoice'], name='purchases_p_company_02e766_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['company', 'product'], name='purchases_p_company_23afaf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasestatushistory',
            index=models.Index(fields=['company', 'invoice'], name='purchases_p_company_278ec1_idx'),
        ),
    ]
