# Generated by Django 5.1.15 on 2026-07-08 08:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_moneyaccount_moneymovement_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='money_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='payments.moneyaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_payable_posted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
