// Bilingual [ar, en] screen titles, extracted from App.tsx.
import type { TenantScreen } from "@/shared/types/navigation";

export const TENANT_TITLES: Record<TenantScreen, [string, string]> = {
  dashboard: ["الرئيسية", "Dashboard"], sales: ["فواتير البيع", "Sales Invoices"],
  "sales-list": ["فواتير البيع", "Sales Invoices"], "sales-new": ["فاتورة بيع جديدة", "New Sales Invoice"],
  "sales-edit": ["تعديل فاتورة بيع", "Edit Sales Invoice"],
  "sales-preview": ["طباعة الفاتورة", "Print Invoice"], "sales-detail": ["تفاصيل الفاتورة", "Invoice Detail"],
  purchases: ["فواتير الشراء", "Purchase Invoices"], "purchases-list": ["فواتير الشراء", "Purchase Invoices"],
  "purchases-new": ["فاتورة شراء جديدة", "New Purchase Invoice"],
  "purchases-edit": ["تعديل فاتورة شراء", "Edit Purchase Invoice"],
  "purchases-preview": ["سجل الشراء الداخلي", "Internal Purchase Record"],
  "purchases-detail": ["تفاصيل فاتورة الشراء", "Purchase Invoice Detail"],
  customers: ["العملاء", "Customers"], "customers-create": ["إضافة عميل", "Add Customer"],
  "customers-edit": ["تعديل بيانات العميل", "Edit Customer"],
  "customers-profile": ["ملف العميل", "Customer Profile"], "customers-statement": ["كشف حساب", "Account Statement"],
  suppliers: ["الموردين", "Suppliers"], "suppliers-new": ["إضافة مورد", "Add Supplier"],
  "suppliers-edit": ["تعديل بيانات المورد", "Edit Supplier"],
  "supplier-profile": ["ملف المورد", "Supplier Profile"], "supplier-statement": ["كشف حساب مورد", "Supplier Statement"],
  "payments-movements": ["كل الحركات المالية", "All Movements"], "payments-customer-collection": ["تسجيل تحصيل", "Collect"],
  "payments-supplier-payment": ["تسجيل دفعة لمورد", "Pay Supplier"], "payments-customer-refund": ["استرجاع مبلغ للعميل", "Customer Refund"],
  "payments-supplier-refund": ["استرداد مبلغ من المورد", "Supplier Refund"], "payment-receipt-detail": ["تفاصيل الإيصال", "Receipt Detail"],
  "payment-receipt-preview": ["طباعة الإيصال", "Print Receipt"], "payments-method-summary": ["ملخص طرق الدفع", "Payment Methods"],
  "payments-cash-bank": ["الخزنة والحسابات البنكية", "Cash & Bank Accounts"], "payments-report": ["تقرير المدفوعات", "Payments Report"],
  products: ["المنتجات", "Products"], "products-new": ["إضافة منتج", "Add Product"], "products-edit": ["تعديل منتج", "Edit Product"],
  "product-detail": ["تفاصيل المنتج", "Product Detail"], "product-categories": ["تصنيفات المنتجات", "Categories"],
  "products-bulk-setup": ["إعداد دفعة واحدة", "Bulk Setup"], "products-byproducts": ["المنتجات الجانبية", "By-products"],
  "products-import-export": ["استيراد / تصدير", "Import / Export"],
  quotations: ["عروض الأسعار", "Quotations"], "quotations-new": ["عرض سعر جديد", "New Quotation"],
  "quotation-detail": ["تفاصيل عرض السعر", "Quotation Detail"], "quotation-preview": ["معاينة عرض السعر", "Quotation Preview"],
  "quotation-convert": ["تحويل إلى فاتورة", "Convert to Invoice"], "quotation-analytics": ["تحليل عروض الأسعار", "Quotation Analytics"],
  reports: ["التقارير والتحليلات", "Reports & Analytics"], "reports-daily": ["تقرير اليوم", "Daily Report"],
  "reports-sales": ["تقارير المبيعات", "Sales Reports"], "reports-purchases": ["تقارير المشتريات", "Purchase Reports"],
  "reports-inventory": ["تقارير المخزون", "Inventory Reports"], "reports-customers": ["تقارير العملاء", "Customer Reports"],
  "reports-suppliers": ["تقارير الموردين", "Supplier Reports"], "reports-tax": ["تقرير الضريبة", "Tax Report"],
  "reports-profit": ["تقرير صافي الربح", "Profit Report"], "reports-statements": ["مركز كشوف الحساب", "Account Statements"],
  "reports-builder": ["تقرير مخصص", "Custom Report"],
  settings: ["الإعدادات", "Settings"], "settings-company": ["بيانات الشركة", "Company Profile"],
  "settings-users": ["المستخدمين", "Users"], "settings-user-new": ["إضافة مستخدم", "Add User"],
  "settings-user-permissions": ["صلاحيات المستخدم", "User Permissions"], "settings-roles": ["الصلاحيات حسب الدور", "Role Permissions"],
  "settings-sensitive-actions": ["الإجراءات الحساسة", "Sensitive Actions"], "settings-audit": ["سجل العمليات", "Audit Log"],
  "settings-numbering": ["ترقيم المستندات", "Document Numbering"], "settings-vat": ["إعدادات الضريبة", "VAT Settings"],
  "settings-print-templates": ["قوالب الطباعة", "Print Templates"], "settings-transactions": ["إعدادات الفواتير", "Transaction Settings"],
  "settings-invoice-design": ["تصميم الفواتير", "Invoice Design"],
  "settings-plan": ["الباقة والميزات", "Plan & Features"], "settings-security": ["إعدادات الأمان", "Security Settings"],
  expenses: ["المصروفات", "Expenses"], "expenses-list": ["قائمة المصروفات", "Expenses List"],
  "expenses-recurring": ["المصروفات المتكررة", "Recurring Expenses"], "expenses-report": ["تقرير المصروفات", "Expense Report"],
  "expense-detail": ["تفاصيل المصروف", "Expense Detail"], "expense-voucher": ["سند مصروف", "Expense Voucher"],
  inventory: ["المخزون", "Inventory"], "inventory-product": ["تفاصيل المنتج", "Product Detail"],
  "inventory-stocktaking": ["جرد المخزون", "Stocktaking"], "inventory-alerts": ["تنبيهات المخزون", "Low Stock Alerts"],
  "inventory-movement": ["حركة المخزون", "Inventory Movement"], "inventory-valuation": ["تقييم المخزون", "Inventory Valuation"],
  payments: ["المدفوعات والتحصيلات", "Payments"], accounts: ["الحسابات", "Accounts"],
  "accounts-list": ["قائمة الحسابات", "Account List"],
  "accounts-new": ["إضافة حساب", "Add Account"],
  "accounts-edit": ["تعديل حساب", "Edit Account"],
  "accounts-detail": ["تفاصيل الحساب", "Account Details"],
  "accounts-statement": ["كشف حساب", "Account Statement"],
  "qa-summary": ["ملخص مراجعة الجودة", "QA Summary"],
  tax: ["إدارة الضريبة VAT", "VAT Management"],
  "tax-sales": ["تقرير ضريبة المبيعات", "Sales VAT Report"],
  "tax-purchases": ["تقرير ضريبة المشتريات", "Purchase VAT Report"],
  "tax-net": ["صافي الضريبة التقديري", "Net VAT Estimate"],
  "tax-warnings": ["تحذيرات الضريبة", "Tax Warnings"],
  "tax-audit": ["سجل تغييرات الضريبة", "VAT Audit Log"],
  "tax-credit-notes": ["الإشعارات الدائنة الضريبية", "Tax Credit Notes"],
  "tax-non-taxable": ["فواتير بدون ضريبة", "Non-Taxable Invoices"],
  "tax-settings": ["إعدادات الضريبة", "Tax Settings"],
  "tax-export-preview": ["تصدير تقرير الضريبة", "Export Tax Report"],
  users: ["المستخدمين والصلاحيات", "Users & Permissions"],
};

export const SUPER_ADMIN_TITLES: Record<string, [string, string]> = {
  dashboard: ["الرئيسية", "Dashboard"], companies: ["الشركات", "Companies"],
  "company-detail": ["تفاصيل الشركة", "Company Details"],
  "company-edit": ["تعديل بيانات الشركة", "Edit Company Details"],
  "create-company": ["إضافة شركة جديدة", "New Company"],
  payments: ["المدفوعات", "Payments"], outstanding: ["المبالغ المستحقة", "Outstanding"],
  plans: ["الخطط والأسعار", "Plans & Pricing"], "audit-log": ["سجل العمليات", "Audit Log"], settings: ["الإعدادات", "Settings"],
};
