# Generated by Django 5.1.15 on 2026-07-01 13:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=64)),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('output_vat_increase', 'Output VAT Increase'), ('output_vat_decrease', 'Output VAT Decrease'), ('input_vat_increase', 'Input VAT Increase'), ('input_vat_decrease', 'Input VAT Decrease'), ('rounding_adjustment', 'Rounding Adjustment'), ('other', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('related_source_type', models.CharField(blank=True, max_length=32)),
                ('related_source_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=16)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_adjustments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_adjustments_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
                'indexes': [models.Index(fields=['company', 'adjustment_date'], name='tax_taxadju_company_57573b_idx'), models.Index(fields=['company', 'status'], name='tax_taxadju_company_a1eafd_idx'), models.Index(fields=['company', 'adjustment_type'], name='tax_taxadju_company_81d8df_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'adjustment_number'), name='uniq_company_tax_adjustment_number')],
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_periods_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_periods_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_periods_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['company', 'start_date', 'end_date'], name='tax_taxperi_company_2a2146_idx'), models.Index(fields=['company', 'status'], name='tax_taxperi_company_026b5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_company_tax_period_name')],
            },
        ),
        migrations.CreateModel(
            name='TaxWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('company_trn_missing', 'Company TRN Missing'), ('customer_trn_missing', 'Customer TRN Missing'), ('supplier_trn_missing', 'Supplier TRN Missing'), ('vat_disabled_sales', 'VAT Disabled on Sales'), ('vat_disabled_purchase', 'VAT Disabled on Purchase'), ('vat_disabled_expense', 'VAT Disabled on Expense'), ('vat_rate_changed', 'VAT Rate Changed'), ('vat_amount_mismatch', 'VAT Amount Mismatch'), ('sales_invoice_cancelled', 'Sales Invoice Cancelled'), ('purchase_invoice_cancelled', 'Purchase Invoice Cancelled'), ('expense_cancelled', 'Expense Cancelled'), ('quotation_not_tax_invoice', 'Quotation Not Tax Invoice'), ('missing_print_template_tax_fields', 'Missing Print Template Tax Fields'), ('other', 'Other')], max_length=48)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('source_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('expense', 'Expense'), ('quotation', 'Quotation'), ('company_settings', 'Company Settings'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('other', 'Other')], max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_warnings_dismissed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_warnings_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'warning_type'], name='tax_taxwarn_company_765eee_idx'), models.Index(fields=['company', 'severity'], name='tax_taxwarn_company_9be758_idx'), models.Index(fields=['company', 'status'], name='tax_taxwarn_company_cdc96e_idx'), models.Index(fields=['company', 'source_type', 'source_id'], name='tax_taxwarn_company_42264f_idx')],
            },
        ),
    ]
