/** Tenant API path segments (append to `/v1`). */
export const ENDPOINTS = {
  auth: {
    login: "/auth/login/",
    refresh: "/auth/refresh/",
    logout: "/auth/logout/",
    me: "/auth/me/",
  },
  admin: {
    companies: "/admin/companies/",
    company: (id: number | string) => `/admin/companies/${id}/`,
    plans: "/admin/plans/",
    subscriptionPayments: "/admin/subscription-payments/",
  },
  tenant: {
    products: "/tenant/products/",
    product: (id: number | string) => `/tenant/products/${id}/`,
    productCategories: "/tenant/product-categories/",
    customers: "/tenant/customers/",
    customer: (id: number | string) => `/tenant/customers/${id}/`,
    customerCategories: "/tenant/customer-categories/",
    suppliers: "/tenant/suppliers/",
    supplier: (id: number | string) => `/tenant/suppliers/${id}/`,
    supplierCategories: "/tenant/supplier-categories/",
    inventory: "/tenant/inventory/",
    inventorySummary: "/tenant/inventory/summary/",
    inventoryLowStock: "/tenant/inventory/low-stock/",
    inventoryMovements: "/tenant/inventory/movements/",
    inventoryProduct: (productId: number | string) => `/tenant/inventory/products/${productId}/`,
    inventoryAdjustments: "/tenant/inventory/adjustments/",
    inventoryOpeningStock: "/tenant/inventory/opening-stock/",
    inventoryStocktaking: "/tenant/inventory/stocktaking/",
    inventoryStocktakingSession: (id: number | string) => `/tenant/inventory/stocktaking/${id}/`,
    inventoryValuation: "/tenant/inventory/valuation/",
    purchases: "/tenant/purchases/",
    purchase: (id: number | string) => `/tenant/purchases/${id}/`,
    purchasesSummary: "/tenant/purchases/summary/",
    sales: "/tenant/sales/",
    sale: (id: number | string) => `/tenant/sales/${id}/`,
    salesSummary: "/tenant/sales/summary/",
    salesPricePreview: "/tenant/sales/price-preview/",
    salesStockCheck: "/tenant/sales/stock-check/",
    paymentsMovements: "/tenant/payments/movements/",
    paymentsSummary: "/tenant/payments/summary/",
    paymentsCustomerCollections: "/tenant/payments/customer-collections/",
    paymentsSupplierPayments: "/tenant/payments/supplier-payments/",
    paymentsCustomerRefunds: "/tenant/payments/customer-refunds/",
    paymentsSupplierRefunds: "/tenant/payments/supplier-refunds/",
    receipts: "/tenant/receipts/",
    receipt: (id: number | string) => `/tenant/receipts/${id}/`,
    quotations: "/tenant/quotations/",
    quotation: (id: number | string) => `/tenant/quotations/${id}/`,
    quotationsSummary: "/tenant/quotations/summary/",
    quotationsPricePreview: "/tenant/quotations/price-preview/",
    expenseCategories: "/tenant/expense-categories/",
    expenses: "/tenant/expenses/",
    expense: (id: number | string) => `/tenant/expenses/${id}/`,
    expensesSummary: "/tenant/expenses/summary/",
    recurringExpenses: "/tenant/recurring-expenses/",
    taxSummary: "/tenant/tax/summary/",
    taxSalesVat: "/tenant/tax/sales-vat/",
    taxPurchaseVat: "/tenant/tax/purchase-vat/",
    taxExpenseVat: "/tenant/tax/expense-vat/",
    taxNetVat: "/tenant/tax/net-vat/",
    taxWarnings: "/tenant/tax/warnings/",
    taxWarningsGenerate: "/tenant/tax/warnings/generate/",
    taxAdjustments: "/tenant/tax/adjustments/",
    taxDisabledVatDocuments: "/tenant/tax/disabled-vat-documents/",
    taxExportPayload: "/tenant/tax/export-payload/",
    reportsDashboard: "/tenant/reports/dashboard/",
    reportsSales: "/tenant/reports/sales/",
    reportsPurchases: "/tenant/reports/purchases/",
    reportsInventory: "/tenant/reports/inventory/",
    reportsInventoryMovements: "/tenant/reports/inventory-movements/",
    reportsCustomerStatement: (customerId: number | string) =>
      `/tenant/reports/customers/${customerId}/statement/`,
    reportsSupplierStatement: (supplierId: number | string) =>
      `/tenant/reports/suppliers/${supplierId}/statement/`,
    reportsPayments: "/tenant/reports/payments/",
    reportsExpenses: "/tenant/reports/expenses/",
    reportsProfit: "/tenant/reports/profit/",
    reportsTaxSummary: "/tenant/reports/tax-summary/",
    reportsExportPayload: "/tenant/reports/export-payload/",
    settings: "/tenant/settings/",
    settingsCompany: "/tenant/settings/company/",
    settingsVat: "/tenant/settings/vat/",
    settingsNumbering: "/tenant/settings/numbering/",
    settingsNumberingItem: (id: number | string) => `/tenant/settings/numbering/${id}/`,
    settingsPrintTemplates: "/tenant/settings/print-templates/",
    settingsPrintTemplate: (id: number | string) => `/tenant/settings/print-templates/${id}/`,
    users: "/tenant/users/",
    user: (id: number | string) => `/tenant/users/${id}/`,
    userPermissions: (id: number | string) => `/tenant/users/${id}/permissions/`,
    userSuspend: (id: number | string) => `/tenant/users/${id}/suspend/`,
    userReactivate: (id: number | string) => `/tenant/users/${id}/reactivate/`,
    permissions: "/tenant/permissions/",
    auditLogs: "/tenant/audit-logs/",
    customerSales: (customerId: number | string) => `/tenant/customers/${customerId}/sales/`,
    customerCollections: (customerId: number | string) => `/tenant/customers/${customerId}/collections/`,
    customerQuotations: (customerId: number | string) => `/tenant/customers/${customerId}/quotations/`,
    customerFreeProducts: (customerId: number | string) => `/tenant/customers/${customerId}/free-products/`,
    supplierPurchases: (supplierId: number | string) => `/tenant/suppliers/${supplierId}/purchases/`,
    supplierPayments: (supplierId: number | string) => `/tenant/suppliers/${supplierId}/payments/`,
    supplierAgreements: (supplierId: number | string) => `/tenant/suppliers/${supplierId}/agreements/`,
    expenseVoucherPreview: (id: number | string) => `/tenant/expenses/${id}/voucher-preview/`,
    receiptPrintPreview: (id: number | string) => `/tenant/receipts/${id}/print-preview/`,
    paymentMovementPrintPreview: (id: number | string) => `/tenant/payments/movements/${id}/print-preview/`,
    purchaseAttachments: (id: number | string) => `/tenant/purchases/${id}/attachments/`,
    expenseAttachments: (id: number | string) => `/tenant/expenses/${id}/attachments/`,
  },
} as const;
