# Generated by Django 5.1.4 on 2026-06-29 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emirate', models.CharField(blank=True, max_length=64)),
                ('trn', models.CharField(blank=True, max_length=32)),
                ('supplier_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit', 'Credit')], default='cash', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance_type', models.CharField(choices=[('we_owe_supplier', 'We owe supplier'), ('supplier_owes_us', 'Supplier owes us'), ('zero', 'Zero')], default='zero', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('track_balance', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.CharField(choices=[('payment_terms', 'Payment Terms'), ('slaughter_deduction', 'Slaughter Deduction'), ('transport_deduction', 'Transport Deduction'), ('loading_unloading_cost', 'Loading/Unloading Cost'), ('vat_behavior', 'VAT Behavior'), ('default_pieces_per_carton', 'Default Pieces Per Carton'), ('default_purchase_method', 'Default Purchase Method'), ('general_note', 'General Note'), ('special_agreement', 'Special Agreement')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applies_automatically', models.BooleanField(default=False)),
                ('suggestion_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_agreements/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_agreements_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_agreements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'supplier categories',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='suppliers.suppliercategory'),
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase_invoice', 'Purchase Invoice'), ('supplier_payment', 'Supplier Payment'), ('purchase_deduction', 'Purchase Deduction'), ('purchase_cancellation', 'Purchase Cancellation'), ('purchase_return', 'Purchase Return'), ('manual_adjustment', 'Manual Adjustment')], max_length=24)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('entry_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_type', models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece'), ('carton', 'Per Carton'), ('tray', 'Per Tray')], default='kg', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_special_prices_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_special_prices', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_special_prices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='suppliercategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_suppliercategory_code'),
        ),
        migrations.AddConstraint(
            model_name='suppliercategory',
            constraint=models.UniqueConstraint(fields=('company', 'name_ar'), name='uniq_company_suppliercategory_name_ar'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'name_ar'], name='suppliers_s_company_f1f542_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'phone'], name='suppliers_s_company_d378dd_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'is_active'], name='suppliers_s_company_429547_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('trn', ''), _negated=True), fields=('company', 'trn'), name='uniq_company_supplier_trn'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['company', 'supplier', 'entry_date'], name='suppliers_s_company_0d9c25_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='suppliers_s_referen_e15aa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierspecialprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'supplier', 'product', 'price_type'), name='uniq_active_supplier_special_price'),
        ),
    ]
