# Generated by Django 5.1.15 on 2026-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase_invoice', 'Purchase Invoice'), ('supplier_payment', 'Supplier Payment'), ('supplier_refund', 'Supplier Refund'), ('purchase_deduction', 'Purchase Deduction'), ('purchase_cancellation', 'Purchase Cancellation'), ('purchase_return', 'Purchase Return'), ('manual_adjustment', 'Manual Adjustment')], max_length=24),
        ),
    ]
