# Generated by Django 5.1.15 on 2026-07-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplierledgerentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit', 'Credit / On Account'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
