# Generated by Django 5.1.4 on 2026-06-29 16:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat_enabled_default', models.BooleanField(default=True)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('allow_vat_disable_sales', models.BooleanField(default=True)),
                ('allow_vat_disable_purchase', models.BooleanField(default=True)),
                ('require_reason_for_vat_change', models.BooleanField(default=True)),
                ('warn_missing_customer_trn', models.BooleanField(default=True)),
                ('warn_missing_supplier_trn', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_settings', to='tenants.company')),
            ],
            options={
                'verbose_name': 'VAT settings',
                'verbose_name_plural': 'VAT settings',
            },
        ),
        migrations.CreateModel(
            name='NumberingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('quotation', 'Quotation'), ('customer_receipt', 'Customer Receipt'), ('supplier_payment_receipt', 'Supplier Payment Receipt'), ('expense_voucher', 'Expense Voucher'), ('collection_adjustment', 'Collection Adjustment'), ('stock_adjustment', 'Stock Adjustment'), ('customer_refund', 'Customer Refund'), ('supplier_refund', 'Supplier Refund')], max_length=32)),
                ('prefix', models.CharField(blank=True, max_length=16)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_length', models.PositiveSmallIntegerField(default=5)),
                ('reset_rule', models.CharField(choices=[('none', 'Never'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_settings', to='tenants.company')),
            ],
            options={
                'ordering': ['document_type'],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type'), name='uniq_company_document_numbering')],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('sales_tax_invoice', 'Sales Tax Invoice'), ('quotation', 'Quotation'), ('purchase_internal_record', 'Purchase Internal Record'), ('customer_receipt', 'Customer Receipt'), ('supplier_payment_receipt', 'Supplier Payment Receipt'), ('expense_voucher', 'Expense Voucher'), ('customer_statement', 'Customer Statement'), ('supplier_statement', 'Supplier Statement'), ('daily_report', 'Daily Report'), ('vat_report', 'VAT Report')], max_length=32)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_stamp', models.BooleanField(default=False)),
                ('show_signature', models.BooleanField(default=False)),
                ('show_trn', models.BooleanField(default=True)),
                ('show_arabic_labels', models.BooleanField(default=True)),
                ('show_english_labels', models.BooleanField(default=True)),
                ('show_amount_in_words', models.BooleanField(default=False)),
                ('footer_notes', models.TextField(blank=True)),
                ('receiver_signature_required', models.BooleanField(default=False)),
                ('paper_size', models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('thermal_80', 'Thermal 80mm')], default='a4', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='tenants.company')),
            ],
            options={
                'ordering': ['template_type'],
                'constraints': [models.UniqueConstraint(fields=('company', 'template_type'), name='uniq_company_template_type')],
            },
        ),
    ]
