# Generated by Django 5.1.4 on 2026-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingsettings',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('quotation', 'Quotation'), ('customer_receipt', 'Customer Receipt'), ('supplier_payment_receipt', 'Supplier Payment Receipt'), ('expense_voucher', 'Expense Voucher'), ('collection_adjustment', 'Collection Adjustment'), ('stock_adjustment', 'Stock Adjustment'), ('customer_refund', 'Customer Refund'), ('supplier_refund', 'Supplier Refund'), ('tax_adjustment', 'Tax Adjustment')], max_length=32),
        ),
    ]
