# Generated by Django 5.1.15 on 2026-07-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_alter_numberingsettings_document_type'),
        ('tenants', '0003_company_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_template_key', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('bilingual', 'Bilingual'), ('firstview_style', 'FirstView Style')], default='firstview_style', max_length=32)),
                ('invoice_color_theme', models.CharField(choices=[('navy_red', 'Navy / Red'), ('royal_blue', 'Royal Blue'), ('emerald', 'Emerald'), ('charcoal_gold', 'Charcoal / Gold'), ('teal', 'Teal'), ('crimson', 'Crimson'), ('purple', 'Purple')], default='navy_red', max_length=32)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_stamp', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('show_company_trn', models.BooleanField(default=True)),
                ('show_company_phone', models.BooleanField(default=True)),
                ('show_customer_trn', models.BooleanField(default=True)),
                ('show_supplier_trn', models.BooleanField(default=True)),
                ('show_bilingual_labels', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_design', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Invoice design settings',
                'verbose_name_plural': 'Invoice design settings',
            },
        ),
    ]
