# Generated by Django 5.1.4 on 2026-06-29 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('sales_invoice', 'Sales Invoice'), ('collection', 'Collection'), ('collection_discount', 'Collection Discount'), ('sales_return', 'Sales Return'), ('tax_credit_note', 'Tax Credit Note'), ('manual_adjustment', 'Manual Adjustment')], max_length=24)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('entry_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_type', models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece'), ('carton', 'Per Carton'), ('tray', 'Per Tray')], default='kg', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'customer categories',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emirate', models.CharField(blank=True, max_length=64)),
                ('trn', models.CharField(blank=True, max_length=32)),
                ('customer_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance_type', models.CharField(choices=[('customer_owes_us', 'Customer owes us'), ('we_owe_customer', 'We owe customer'), ('zero', 'Zero')], default='zero', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('block_sales_when_credit_exceeded', models.BooleanField(default=True)),
                ('allow_admin_credit_override', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customercategory')),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditLimitChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('change_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary_for_invoice', 'Temporary (for invoice)')], default='permanent', max_length=24)),
                ('related_reference_type', models.CharField(blank=True, max_length=64)),
                ('related_reference_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_limit_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_limit_changes', to='customers.customer')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFreeProductAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.CharField(choices=[('always_free', 'Always Free'), ('free_when_selected', 'Free When Selected'), ('minimum_invoice_amount', 'Minimum Invoice Amount'), ('minimum_quantity', 'Minimum Quantity')], max_length=24)),
                ('condition_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('condition_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_free_agreements_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_product_agreements', to='customers.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
