# Generated by Django 5.1.4 on 2026-06-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfreeproductagreement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_free_agreements', to='products.product'),
        ),
        migrations.AddField(
            model_name='customerfreeproductagreement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_free_agreements_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerspecialprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='customerspecialprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_special_prices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerspecialprice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerspecialprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_special_prices', to='products.product'),
        ),
        migrations.AddField(
            model_name='customerspecialprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_special_prices_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customercategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_customercategory_code'),
        ),
        migrations.AddConstraint(
            model_name='customercategory',
            constraint=models.UniqueConstraint(fields=('company', 'name_ar'), name='uniq_company_customercategory_name_ar'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'name_ar'], name='customers_c_company_05815d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone'], name='customers_c_company_e97128_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_active'], name='customers_c_company_ecdc25_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('trn', ''), _negated=True), fields=('company', 'trn'), name='uniq_company_customer_trn'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['company', 'customer', 'entry_date'], name='customers_c_company_0a1610_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='customers_c_referen_b73452_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerspecialprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'customer', 'product', 'price_type'), name='uniq_active_customer_special_price'),
        ),
    ]
