# Generated by Django 5.1.15 on 2026-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('sales_invoice', 'Sales Invoice'), ('collection', 'Collection'), ('collection_discount', 'Collection Discount'), ('customer_refund', 'Customer Refund'), ('sales_return', 'Sales Return'), ('tax_credit_note', 'Tax Credit Note'), ('manual_adjustment', 'Manual Adjustment')], max_length=24),
        ),
    ]
