# Generated by Django 5.1.4 on 2026-06-29 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(help_text="e.g. 'primefresh' -> primefresh.poultryhero.solutions", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase letters, numbers, or hyphens only (no spaces or special characters), and start/end with a letter or number.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')])),
                ('trade_license', models.CharField(blank=True, max_length=64)),
                ('trn', models.CharField(blank=True, max_length=32, verbose_name='Tax Registration Number')),
                ('country', models.CharField(default='UAE', max_length=64)),
                ('emirate', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company/stamp/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company/signature/')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='trial', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['status'], name='tenants_com_status_dc54db_idx'), models.Index(fields=['subdomain'], name='tenants_com_subdoma_4e62e7_idx')],
            },
        ),
    ]
