# Generated by Django 5.1.4 on 2026-07-05 08:08

import apps.tenants.models
import apps.tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.company_logo_upload_path, validators=[apps.tenants.validators.validate_company_image_extension, apps.tenants.validators.validate_company_image_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.company_signature_upload_path, validators=[apps.tenants.validators.validate_company_image_extension, apps.tenants.validators.validate_company_image_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.company_stamp_upload_path, validators=[apps.tenants.validators.validate_company_image_extension, apps.tenants.validators.validate_company_image_size]),
        ),
    ]
