# Generated by Django 5.1.15 on 2026-07-01 09:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customerledgerentry_entry_type'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(max_length=64)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('customer_trn_snapshot', models.CharField(blank=True, max_length=32)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=32)),
                ('customer_address_snapshot', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_accepted', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_converted', to=settings.AUTH_USER_MODEL)),
                ('converted_sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='sales.salesinvoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_rejected', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_sent', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('product_sku_snapshot', models.CharField(blank=True, max_length=64)),
                ('line_type', models.CharField(choices=[('product', 'Product'), ('by_product', 'By-product'), ('service', 'Service'), ('other', 'Other')], default='product', max_length=16)),
                ('quantity_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_pieces', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_type', models.CharField(default='kg', max_length=16)),
                ('price_source', models.CharField(choices=[('default_product_price', 'Default Product Price'), ('customer_special_price', 'Customer Special Price'), ('manual_override', 'Manual Override'), ('free_product', 'Free Product')], default='default_product_price', max_length=32)),
                ('is_free', models.BooleanField(default=False)),
                ('free_reason', models.TextField(blank=True)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_status_history', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='quotations.quotation')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'customer'], name='quotations__company_a4815c_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'status'], name='quotations__company_a4be29_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'quotation_date'], name='quotations__company_fb5081_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'valid_until'], name='quotations__company_0ea828_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('company', 'quotation_number'), name='uniq_company_quotation_number'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['company', 'quotation'], name='quotations__company_6784be_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['company', 'product'], name='quotations__company_ef7da1_idx'),
        ),
    ]
