# Generated by Django 5.1.15 on 2026-07-01 09:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customerledgerentry_entry_type'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0002_alter_supplierledgerentry_entry_type'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_number', models.CharField(max_length=64)),
                ('receipt_number', models.CharField(blank=True, max_length=64)),
                ('movement_type', models.CharField(choices=[('customer_collection', 'Customer Collection'), ('supplier_payment', 'Supplier Payment'), ('customer_refund', 'Customer Refund'), ('supplier_refund', 'Supplier Refund'), ('collection_adjustment', 'Collection Adjustment'), ('supplier_adjustment', 'Supplier Adjustment'), ('other', 'Other')], max_length=32)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=16)),
                ('movement_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=128)),
                ('cheque_number', models.CharField(blank=True, max_length=64)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=16)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_movements_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_movements', to='customers.customer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_movements_posted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_movements', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('account_level', 'Account Level')], max_length=24)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchases.purchaseinvoice')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.salesinvoice')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.paymentmovement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_history', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.paymentmovement')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'movement_type'], name='payments_pa_company_bc858e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'party_type'], name='payments_pa_company_b53579_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'customer'], name='payments_pa_company_59ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'supplier'], name='payments_pa_company_067f54_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'movement_date'], name='payments_pa_company_958c58_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmovement',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_55f0cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmovement',
            constraint=models.UniqueConstraint(fields=('company', 'movement_number'), name='uniq_company_payment_movement_number'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'movement'], name='payments_pa_company_074a64_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'sales_invoice'], name='payments_pa_company_23a660_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'purchase_invoice'], name='payments_pa_company_30f2d1_idx'),
        ),
    ]
