# Generated by Django 5.1.15 on 2026-07-08 08:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0003_company_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('cashbox', 'Cashbox'), ('bank', 'Bank')], max_length=16)),
                ('bank_name', models.CharField(blank=True, max_length=128)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_negative', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
            ],
            options={
                'ordering': ['account_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MoneyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_payment', 'Purchase Payment'), ('supplier_payment', 'Supplier Payment'), ('customer_collection', 'Customer Collection'), ('expense_payment', 'Expense Payment'), ('manual_adjustment', 'Manual Adjustment'), ('refund', 'Refund'), ('opening_balance', 'Opening Balance')], max_length=32)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_movements_created', to=settings.AUTH_USER_MODEL)),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='payments.moneyaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='moneyaccount',
            index=models.Index(fields=['company', 'account_type'], name='payments_mo_company_f5d53f_idx'),
        ),
        migrations.AddIndex(
            model_name='moneyaccount',
            index=models.Index(fields=['company', 'is_active'], name='payments_mo_company_0052dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='moneyaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_company_money_account_name'),
        ),
        migrations.AddIndex(
            model_name='moneymovement',
            index=models.Index(fields=['company', 'money_account'], name='payments_mo_company_2b1f29_idx'),
        ),
        migrations.AddIndex(
            model_name='moneymovement',
            index=models.Index(fields=['company', 'movement_type'], name='payments_mo_company_789c79_idx'),
        ),
        migrations.AddIndex(
            model_name='moneymovement',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='payments_mo_company_a63e84_idx'),
        ),
    ]
