# Generated by Django 5.1.4 on 2026-06-29 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('product_type', models.CharField(choices=[('fixed_weight', 'Fixed Weight'), ('moving_weight', 'Moving/Custom Weight'), ('by_product', 'By-product'), ('chicken_part', 'Chicken Part'), ('service', 'Service'), ('other', 'Other')], max_length=20)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('default_pieces_per_carton', models.PositiveIntegerField(blank=True, null=True)),
                ('default_unit', models.CharField(choices=[('kg', 'KG'), ('piece', 'Piece'), ('carton', 'Carton'), ('tray', 'Tray')], default='carton', max_length=10)),
                ('sales_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sales_price_type', models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece'), ('carton', 'Per Carton'), ('tray', 'Per Tray')], default='kg', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_price_type', models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece'), ('carton', 'Per Carton'), ('tray', 'Per Tray')], default='kg', max_length=10)),
                ('minimum_stock_cartons', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_stock_pieces', models.PositiveIntegerField(default=0)),
                ('minimum_stock_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('track_inventory', models.BooleanField(default=True)),
                ('vat_taxable', models.BooleanField(default=True)),
                ('allow_customer_special_price', models.BooleanField(default=True)),
                ('allow_supplier_special_price', models.BooleanField(default=True)),
                ('allow_free_product', models.BooleanField(default=True)),
                ('can_sell', models.BooleanField(default=True)),
                ('can_purchase', models.BooleanField(default=True)),
                ('can_quote', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disable_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.company')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_disabled', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_productcategory_code'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name_ar'), name='uniq_company_productcategory_name_ar'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'product_type'], name='products_pr_company_fa313c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='products_pr_company_088709_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'category'], name='products_pr_company_df3bdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uniq_company_product_sku'),
        ),
    ]
